### ISSUE TITLE
Possible to Tag Files in Scripto?

### ISSUE THREAD

**Issue by mhshaaban** [Daniel-KM/Omeka-plugin-Tagging#1]
Is it possible to modify this plugin to allow public tagging of files used alongside the scripto plugin?

**Comment by Daniel-KM** [comment]
Hi,

By default, Omeka doesn't allow to tag files, but only items, even it the source code allows it (the table for tags stores the record type). The plugin uses the standard tags, so it's not possible currently. It may be possible to tag anything (collections too) only if some changes are made in the core or in the plugin.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
